#########
## REDIRECTIONS
#########
[[redirects]]
  from = "/fr/galerie"
  to = "/fr/galerie/cotid/"
  status = 301
  force = true
[[redirects]]
  from = "/es/galeria"
  to = "/es/galeria/cotid/"
  status = 301
  force = true
[[redirects]]
  from = "/gallery"
  to = "/gallery/cotid/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/expositions"
  to = "/fr/expositions/individuelle/"
  status = 301
  force = true
[[redirects]]
  from = "/es/exposiciones"
  to = "/es/exposiciones/individual/"
  status = 301
  force = true
[[redirects]]
  from = "/exhibitions"
  to = "/exhibitions/individual/"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404
  force = true

[[redirects]]
  from = "/es/*"
  to = "/es/404/"
  status = 404
  force = true

[[redirects]]
  from = "/fr/*"
  to = "/fr/404/"
  status = 404
  force = true


#########
## CONFIG
#########
[build]
  command = "npm run build"
  publish = "dist"

[context.staging]
    command = "npm run stage"
    publish = "stage"