---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: "Français \U0001F1EB\U0001F1F7"
- type: document
  path: "./site/content/about/_index.fr.md"
  label: A propos
  match: "**/*"
- type: directory
  path: "./site/content"
  label: Pages
  create: all
  match: "*"
- type: document
  path: "./site/content/about/_index.en.md"
  label: About 2
- type: directory
  path: "./site/content/collectors"
  label: Collectors
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/credits"
  label: Credits
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/serie1"
  label: Serie1
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/contact"
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/about"
  label: About
  create: documents
  match: "**/*"
- type: directory
  path: "./site/content/exhibitions"
  label: Exhibitions
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/legal"
  label: Legal
  create: all
  match: "**/*"
upload_dir: "./site/static/uploads"
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
