baseURL = "https://gabriel-cuallado.netlify.app/"
DefaultContentLanguage = "en"
title = "Gabriel Cuallado"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
    [languages.en]
        weight = 1

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.main]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/serie1"
                weight = 2
            [[languages.en.menu.main]]
                identifier = "Expositions"
                name = "Exhibitions"
                url = "/exhibitions/"
                weight = 3
            [[languages.en.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4

            [[languages.en.menu.header]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.header]]
                identifier = "Exhibitions"
                name = "Exhibitions"
                url = "/exhibitions/"
                weight = 2
            [[languages.en.menu.header]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/serie1/"
                weight = 3

            

            
            [[languages.en.menu.about]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.about]]
                identifier = "Collectors"
                name = "Collectors"
                url = "/collectors/"
                weight = 2
            [[languages.en.menu.about]]
                identifier = "Awards"
                name = "Awards"
                url = "/awards/"
                weight = 3
            [[languages.en.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/publications/"
                weight = 4

            [[languages.en.menu.exhibitions]]
                identifier = "Individual"
                name = "Individual"
                url = "/exhibitions/"
                weight = 1
            [[languages.en.menu.exhibitions]]
                identifier = "Collective"
                name = "Collective"
                url = "/exhibitions-collective/"
                weight = 2


    [languages.es]
        weight = 2
        [languages.es.menu]
            [[languages.es.menu.main]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.main]]
                identifier = "Gallery"
                name = "Galeria"
                url = "/es/gallery/serie1"
                weight = 2
            [[languages.es.menu.main]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/"
                weight = 3
            [[languages.es.menu.main]]
                identifier = "Contact"
                name = "Contactos"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4


            [[languages.es.menu.header]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.header]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/"
                weight = 2
             [[languages.es.menu.header]]
                identifier = "Galeria"
                name = "Galeria"
                url = "/es/gallery/serie1/"
                weight = 3
                

            [[languages.es.menu.about]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.about]]
                identifier = "Collectors"
                name = "Coleccionistas"
                url = "/es/coleccionistas/"
                weight = 2
            [[languages.es.menu.about]]
                identifier = "Awards"
                name = "Premios"
                url = "/es/premios/"
                weight = 3
            [[languages.es.menu.about]]
                identifier = "Publications"
                name = "Publicaciones"
                url = "/es/publicaciones/"
                weight = 4


            [[languages.es.menu.exhibitions]]
                identifier = "esIndividual"
                name = "Individuales"
                url = "/es/exposiciones/"
                weight = 1
            [[languages.es.menu.exhibitions]]
                identifier = "esCollective"
                name = "Colectivas"
                url = "/es/exposiciones-colectivas/" 
                weight = 2

    [languages.fr]
        weight = 3
        [languages.fr.menu]
            [[languages.fr.menu.main]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.main]]
                identifier = "Gallery"
                name = "Galerie"
                url = "/fr/gallery/serie1"
                weight = 2
            [[languages.fr.menu.main]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/"
                weight = 3
            [[languages.fr.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4


            [[languages.fr.menu.header]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.header]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/"
                weight = 2
            [[languages.fr.menu.header]]
                identifier = "Galerie"
                name = "Galerie"
                url = "/fr/gallery/serie1/"
                weight = 3
            

            [[languages.fr.menu.about]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.about]]
                identifier = "Collectors"
                name = "Collections"
                url = "/fr/collections"
                weight = 2
            [[languages.fr.menu.about]]
                identifier = "Awards"
                name = "Prix"
                url = "/fr/prix/"
                weight = 3
            [[languages.fr.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/fr/publications/"
                weight = 4

            [[languages.fr.menu.exhibitions]]
                identifier = "frIndividual"
                name = "Individuelles"
                url = "/fr/expositions/"
                weight = 1
            [[languages.fr.menu.exhibitions]]
                identifier = "frCollective"
                name = "Collectives"
                url = "/fr/expositions-collectives/" 
                weight = 2
        
