baseURL = "https://gabriel-cuallado.com/"
DefaultContentLanguage = "en"
title = "Gabriel Cuallado"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
    [languages.en]
        weight = 1
        contentDir = "content/english"
        languageName = "English"

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
                [[languages.en.menu.main]]
                    identifier = "Aboutsub"
                    name = "Biography"
                    parent = "About"
                    url = "/about/"
                    weight = 1
                [[languages.en.menu.main]]
                    identifier = "Collectors"
                    name = "Collectors"
                    parent = "About"
                    url = "/about/collectors/"
                    weight = 2
                [[languages.en.menu.main]]
                    name = "Awards"
                    parent = "About"
                    identifier = "Awards"
                    url = "/about/awards/"
                    weight = 3
                [[languages.en.menu.main]]
                    identifier = "Publications"
                    name = "Publications"
                    parent = "About"
                    url = "/about/publications/"
                    weight = 4
                [[languages.en.menu.main]]
                    identifier = "Press"
                    name = "Press"
                    parent = "About"
                    url = "/about/press/"
                    weight = 5
            [[languages.en.menu.main]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/cotid/"
                weight = 2
            [[languages.en.menu.main]]
                identifier = "Expositions"
                name = "Exhibitions"
                url = "/exhibitions/individual/"
                weight = 3
                [[languages.en.menu.main]]
                    identifier = "Individual"
                    name = "Individual"
                    parent = "Expositions"
                    url = "/exhibitions/individual/"
                    weight = 1
                [[languages.en.menu.main]]
                    identifier = "Collective"
                    name = "Collective"
                    parent = "Expositions"
                    url = "/exhibitions/collective/"
                    weight = 2
            [[languages.en.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4

            [[languages.en.menu.header]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.header]]
                identifier = "Exhibitions"
                name = "Exhibitions"
                url = "/exhibitions/individual/"
                weight = 2
            [[languages.en.menu.header]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/cotid/"
                weight = 3
            [[languages.en.menu.header]]
                identifier = "Contact"
                name = "Contact"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4
            
            [[languages.en.menu.about]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.about]]
                identifier = "Collectors"
                name = "Collectors"
                url = "/about/collectors/"
                weight = 2
            [[languages.en.menu.about]]
                identifier = "Awards"
                name = "Awards"
                url = "/about/awards/"
                weight = 3
            [[languages.en.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/about/publications/"
                weight = 4
            [[languages.en.menu.about]]
                identifier = "Press"
                name = "Press"
                url = "/about/press/"
                weight = 5


    [languages.es]
        weight = 2
        contentDir = "content/spanish"
        languageName = "Español"
        [languages.es.menu]
            [[languages.es.menu.main]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
                [[languages.es.menu.main]]
                    identifier = "Aboutsub"
                    name = "biografía"
                    parent = "About"
                    url = "/es/acerca/"
                    weight = 1
                [[languages.es.menu.main]]
                    identifier = "Coleccionistas"
                    name = "Coleccionistas"
                    parent = "About"
                    url = "/es/acerca/coleccionistas/"
                    weight = 2
                [[languages.es.menu.main]]
                    name = "Premios"
                    parent = "About"
                    identifier = "premios"
                    url = "/es/acerca/premios/"
                    weight = 3
                [[languages.es.menu.main]]
                    identifier = "publicaciones"
                    name = "Publicaciones"
                    parent = "About"
                    url = "/es/acerca/publicaciones/"
                    weight = 4
                [[languages.es.menu.main]]
                    identifier = "Prensa"
                    name = "Prensa"
                    parent = "About"
                    url = "/es/acerca/prensa/"
                    weight = 5
            [[languages.es.menu.main]]
                identifier = "Gallery"
                name = "Galeria"
                url = "/es/galeria/cotid/"
                weight = 2
            [[languages.es.menu.main]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/individual/"
                weight = 3
                [[languages.es.menu.main]]
                    identifier = "Individual"
                    name = "Individual"
                    parent = "Expositions"
                    url = "/es/exposiciones/individual/"
                    weight = 1
                [[languages.es.menu.main]]
                    identifier = "Colectivo"
                    name = "Colectivo"
                    parent = "Expositions"
                    url = "/es/exposiciones/colectivo/"
                    weight = 2
            [[languages.es.menu.main]]
                identifier = "Contact"
                name = "Contactos"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4


            [[languages.es.menu.header]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.header]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/individual/"
                weight = 2
             [[languages.es.menu.header]]
                identifier = "Galeria"
                name = "Galeria"
                url = "/es/galeria/cotid/"
                weight = 3
            [[languages.es.menu.header]]
                identifier = "Contact"
                name = "Contactos"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4
                

            [[languages.es.menu.about]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.about]]
                identifier = "Collectors"
                name = "Coleccionistas"
                url = "/es/acerca/coleccionistas/"
                weight = 2
            [[languages.es.menu.about]]
                identifier = "Awards"
                name = "Premios"
                url = "/es/acerca/premios/"
                weight = 3
            [[languages.es.menu.about]]
                identifier = "Publications"
                name = "Publicaciones"
                url = "/es/acerca/publicaciones/"
                weight = 4
            [[languages.es.menu.about]]
                identifier = "Press"
                name = "Prensa"
                url = "/es/acerca/prensa/"
                weight = 5



    [languages.fr]
        weight = 3
        contentDir = "content/french"
        languageName = "Français"
        [languages.fr.menu]
            [[languages.fr.menu.main]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
                [[languages.fr.menu.main]]
                    identifier = "Aboutsub"
                    name = "Biographie"
                    parent = "About"
                    url = "/fr/a-propos/"
                    weight = 1
                [[languages.fr.menu.main]]
                    identifier = "Collectors"
                    name = "Collections"
                    parent = "About"
                    url = "/fr/a-propos/collections/"
                    weight = 2
                [[languages.fr.menu.main]]
                    name = "Prix"
                    parent = "About"
                    identifier = "Prix"
                    url = "/fr/a-propos/prix/"
                    weight = 3
                [[languages.fr.menu.main]]
                    identifier = "Publications"
                    name = "Publications"
                    parent = "About"
                    url = "/fr/a-propos/publications/"
                    weight = 4
                [[languages.fr.menu.main]]
                    identifier = "Press"
                    name = "Presse"
                    parent = "About"
                    url = "/fr/a-propos/presse/"
                    weight = 5
            [[languages.fr.menu.main]]
                identifier = "Gallery"
                name = "Galerie"
                url = "/fr/galerie/cotid/"
                weight = 2
            [[languages.fr.menu.main]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/individuelle/"
                weight = 3
                [[languages.fr.menu.main]]
                    identifier = "Individuelle"
                    name = "Individuelle"
                    parent = "Expositions"
                    url = "/fr/expositions/individuelle/"
                    weight = 1
                [[languages.fr.menu.main]]
                    identifier = "Collective"
                    name = "Collectives"
                    parent = "Expositions"
                    url = "/fr/expositions/collective/"
                    weight = 2
            [[languages.fr.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4


            [[languages.fr.menu.header]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.header]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/individuelle/"
                weight = 2
            [[languages.fr.menu.header]]
                identifier = "Galerie"
                name = "Galerie"
                url = "/fr/galerie/cotid/"
                weight = 3
            [[languages.fr.menu.header]]
                identifier = "Contact"
                name = "Contact"
                url = "https://oko4.typeform.com/to/lvAGfzUG"
                weight = 4
            

            [[languages.fr.menu.about]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.about]]
                identifier = "Collectors"
                name = "Collections"
                url = "/fr/a-propos/collections/"
                weight = 2
            [[languages.fr.menu.about]]
                identifier = "Awards"
                name = "Prix"
                url = "/fr/a-propos/prix/"
                weight = 3
            [[languages.fr.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/fr/a-propos/publications/"
                weight = 4
            [[languages.fr.menu.about]]
                identifier = "Press"
                name = "Presse"
                url = "/fr/a-propos/presse/"
                weight = 5
        
