baseURL = "https://gabriel-cuallado.netlify.com/"
DefaultContentLanguage = "en"
title = "Gabriel Cuallado"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
    [languages.en]
        weight = 1
        [languages.en.menu]
            [[languages.en.menu.exhibitions]]
                identifier = "Individual"
                name = "Individual"
                url = "/exhibitions/"
                weight = 1
            [[languages.en.menu.exhibitions]]
                identifier = "Collective"
                name = "Collective"
                url = "/exhibitions-collective/"
                weight = 2


    [languages.es]
        weight = 2
        [languages.es.menu]
            [[languages.es.menu.exhibitions]]
                identifier = "esIndividual"
                name = "Individuales"
                url = "/es/exhibitions/"
                weight = 1
            [[languages.es.menu.exhibitions]]
                identifier = "esCollective"
                name = "Colectivas"
                url = "/es/exhibitions-collective/" 
                weight = 2

    [languages.fr]
        weight = 3
        [languages.fr.menu]
            [[languages.fr.menu.exhibitions]]
                identifier = "frIndividual"
                name = "Individuelles"
                url = "/fr/exhibitions/"
                weight = 1
            [[languages.fr.menu.exhibitions]]
                identifier = "frCollective"
                name = "Collectives"
                url = "/fr/exhibitions-collective/" 
                weight = 2
        
