baseURL = "https://gabriel-cuallado.netlify.app/"
DefaultContentLanguage = "en"
title = "Gabriel Cuallado"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
    [languages.en]
        weight = 1
        contentDir = "content/english"
        languageName = "English"

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.main]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/serie1"
                weight = 2
            [[languages.en.menu.main]]
                identifier = "Expositions"
                name = "Exhibitions"
                url = "/exhibitions/"
                weight = 3
            [[languages.en.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4

            [[languages.en.menu.header]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.header]]
                identifier = "Exhibitions"
                name = "Exhibitions"
                url = "/exhibitions/individual"
                weight = 2
            [[languages.en.menu.header]]
                identifier = "Gallery"
                name = "Gallery"
                url = "/gallery/serie1/"
                weight = 3

            

            
            [[languages.en.menu.about]]
                identifier = "About"
                name = "About"
                url = "/about/"
                weight = 1
            [[languages.en.menu.about]]
                identifier = "Collectors"
                name = "Collectors"
                url = "/about/collectors/"
                weight = 2
            [[languages.en.menu.about]]
                identifier = "Awards"
                name = "Awards"
                url = "/about/awards/"
                weight = 3
            [[languages.en.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/about/publications/"
                weight = 4


    [languages.es]
        weight = 2
        contentDir = "content/spanish"
        languageName = "Español"
        [languages.es.menu]
            [[languages.es.menu.main]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.main]]
                identifier = "Gallery"
                name = "Galeria"
                url = "/es/galeria/el-rastro/"
                weight = 2
            [[languages.es.menu.main]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/individual"
                weight = 3
            [[languages.es.menu.main]]
                identifier = "Contact"
                name = "Contactos"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4


            [[languages.es.menu.header]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.header]]
                identifier = "Expositions"
                name = "Exposiciones"
                url = "/es/exposiciones/"
                weight = 2
             [[languages.es.menu.header]]
                identifier = "Galeria"
                name = "Galeria"
                url = "/es/galeria/el-rastro/"
                weight = 3
                

            [[languages.es.menu.about]]
                identifier = "About"
                name = "Acerca"
                url = "/es/acerca/"
                weight = 1
            [[languages.es.menu.about]]
                identifier = "Collectors"
                name = "Coleccionistas"
                url = "/es/acerca/coleccionistas/"
                weight = 2
            [[languages.es.menu.about]]
                identifier = "Awards"
                name = "Premios"
                url = "/es/acerca/premios/"
                weight = 3
            [[languages.es.menu.about]]
                identifier = "Publications"
                name = "Publicaciones"
                url = "/es/acerca/publicaciones/"
                weight = 4



    [languages.fr]
        weight = 3
        contentDir = "content/french"
        languageName = "Français"
        [languages.fr.menu]
            [[languages.fr.menu.main]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.main]]
                identifier = "Gallery"
                name = "Galerie"
                url = "/fr/galerie/el-rastro"
                weight = 2
            [[languages.fr.menu.main]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/individuelle"
                weight = 3
            [[languages.fr.menu.main]]
                identifier = "Contact"
                name = "Contact"
                url = "https://gabrielcuallado.typeform.com/to/EfepgT"
                weight = 4


            [[languages.fr.menu.header]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.header]]
                identifier = "Expositions"
                name = "Expositions"
                url = "/fr/expositions/individuelle"
                weight = 2
            [[languages.fr.menu.header]]
                identifier = "Galerie"
                name = "Galerie"
                url = "/fr/galerie/el-rastro"
                weight = 3
            

            [[languages.fr.menu.about]]
                identifier = "About"
                name = "À Propos"
                url = "/fr/a-propos/"
                weight = 1
            [[languages.fr.menu.about]]
                identifier = "Collectors"
                name = "Collections"
                url = "/fr/a-propos/collections/"
                weight = 2
            [[languages.fr.menu.about]]
                identifier = "Awards"
                name = "Prix"
                url = "/fr/a-propos/prix/"
                weight = 3
            [[languages.fr.menu.about]]
                identifier = "Publications"
                name = "Publications"
                url = "/fr/a-propos/publications/"
                weight = 4

            # [[languages.fr.menu.exhibitions]]
            #     identifier = "frIndividual"
            #     name = "Individuelles"
            #     url = "/fr/expositions/"
            #     weight = 1
            # [[languages.fr.menu.exhibitions]]
            #     identifier = "frCollective"
            #     name = "Collectives"
            #     url = "/fr/expositions-collectives/" 
            #     weight = 2
        
