name: Build and Release
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: /dist
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'
        # extended: true
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install, build
      run: |
        npm install
        npm run build
        
    - name: Copy dist
      uses: andstor/copycat-action@v3
      with:
        personal_token: dcb882dbea82ffc515b1be110857e088b835421e
        src_path: /home/runner/work/GabrielCuallado/GabrielCuallado/dist
        dst_owner: alexiscolin
        dst_repo_name: gabrielcuallado-website
        clean: true
        email: alexis@de-jaune-et-de-bleu.com
        username: alexiscolin 
        commit_message: '[GHA] Update the dist folder.'
